### PR TITLE
Postpone downloading NVD in the command-line tool

### LINKED ISSUE #400: Postpone downloading NVD in the command-line tool
The command-line tools starts downloading NVD before validating all input parameters. As a result, it a user runs the tool with invalid input, then it's going to be discovered after downloading NVD. But it can fail earlier without wasting time for downloading NVD.

### PR DESCRIPTION
**Pull request by artem-smotrakov**
Here is a list of main updates:

 - Updated the `NVD` class to download data from NVD if necessary.
- Updated the command-line tool not to download NVD in advance.

Closes #400

### CODE REVIEW

File: src/main/java/com/sap/oss/phosphor/fosstars/nvd/NVD.java [hunk 1]
```diff
@@ -24,7 +26,8 @@
 import us.springett.nistdatamirror.NistDataMirror;
 
 /**
- * This class offers an interface to the NVD.
+ * <p>This class offers an interface to the NVD.</p>
+ * <p>The class is not threat-safe.</p>
```
Comment (mibo) [inline src/main/java/com/sap/oss/phosphor/fosstars/nvd/NVD.java:30]:
```suggestion
 * <p>The class is not thread-safe.</p>
```

**Review by mibo — APPROVED** [review]
Only a minor typo, hence I approved it already 🙂

File: src/main/java/com/sap/oss/phosphor/fosstars/nvd/NVD.java (hunk 1 above)
Comment (artem-smotrakov) [reply src/main/java/com/sap/oss/phosphor/fosstars/nvd/NVD.java:30]: My usual typo! Thanks!
