### PR TITLE
Fix several formatting issues in PrettyPrinter

### LINKED ISSUE #313: Fix several formatting issues in PrettyPrinter
There are several issues with padding, formatting doubles, feature and score names.

### PR DESCRIPTION
**Pull request by artem-smotrakov**
Here is a list of main updates:

- Use `DecimalFormat` to format doubles.
- Added a label for confidence.
- Fixed padding for numbers with max values.
- Added better names for several features and scores.
- Updated the tests.

This fixes #313

### CODE REVIEW

File: src/main/java/com/sap/sgs/phosphor/fosstars/tool/format/PrettyPrinter.java [hunk 1]
```diff
@@ -99,22 +115,25 @@
...
   @Override
   public String print(RatingValue ratingValue) {
     StringBuilder sb = new StringBuilder();
     sb.append(String.format("Here is how the rating was calculated:%n"));
     sb.append(print(ratingValue.scoreValue(), INDENT_STEP, true, new HashSet<>()));
-    sb.append(String.format("Rating: %2.2f out of %2.2f -> %s%n",
-        ratingValue.score(), Score.MAX, ratingValue.label()));
-    sb.append(String.format("Confidence: %2.2f out of %2.2f%n",
-        ratingValue.confidence(), Confidence.MAX));
+    sb.append(String.format("Rating:     %s -> %s%n",
```
Comment (sourabhsparkala) [inline src/main/java/com/sap/sgs/phosphor/fosstars/tool/format/PrettyPrinter.java:132]: There is a tab space in between. Is this a typo? or required?

Comment (artem-smotrakov) [reply src/main/java/com/sap/sgs/phosphor/fosstars/tool/format/PrettyPrinter.java:132]: There is no tab, it's just spaces. Yes, I added it intentionally to align the numbers in Rating and Confidence fields.
