### PR TITLE
Addressing IllegalStateException in OssArtifactSecurityScore

### LINKED ISSUE #820: OssSecurityScore is unknown and OssArtifactSecurityScore is known throws Illegal State Exception
Unavailability of features gives `OssSecurityScore` as `unknown` but when calculating `OssArtifactSecurityScore` an `IllegalStateException` is thrown

```
java.lang.IllegalStateException: It's an unknown value, get() method is not supposed to be called!
	at com.sap.oss.phosphor.fosstars.model.value.ScoreValue.get(ScoreValue.java:144)
	at com.sap.oss.phosphor.fosstars.model.score.oss.OssArtifactSecurityScore.calculate(OssArtifactSecurityScore.java:96)
	at com.sap.oss.phosphor.fosstars.model.score.AbstractScore.calculate(AbstractScore.java:93)
	at com.sap.oss.phosphor.fosstars.model.score.oss.OssArtifactSecurityScoreTest.testCalculateOssSecurityScoreUnknown(OssArtifactSecurityScoreTest.java:66)
```

This exception should not be thrown. The core should rationalize the `OssArtifactSecurityScore` with a `LOW` confidence value.

Things to Do:
- The core should rationalize the `OssArtifactSecurityScore` with a `LOW` confidence value.

### PR DESCRIPTION
**Pull request by sourabhsparkala**
Fixes #820

### CODE REVIEW

File: src/main/java/com/sap/oss/phosphor/fosstars/model/score/oss/OssArtifactSecurityScore.java [hunk 1]
```diff
@@ -88,7 +88,9 @@ public ScoreValue calculate(Value<?>... values) {
     }
```
Comment (mibo) [inline src/main/java/com/sap/oss/phosphor/fosstars/model/score/oss/OssArtifactSecurityScore.java:88]: I would suggest in case of an unknown score (either artifact or project) to return to combined score as unknown.
Because the `OssArtifactSecurityScore` take the project score and modify it based on the artifact version score.
If the project score is unknown it can not be modified and just returning the artifact version score is not correct (IMHO).

Other opinions?

As sample (which requires changes additional changes in line 91ff):
```suggestion
    } else if (projectSecurityScore.isUnknown()) {
      return scoreValue.withMinConfidence().makeUnknown();
    }
```

**Review by mibo — CHANGES_REQUESTED** [review]

File: src/main/java/com/sap/oss/phosphor/fosstars/model/score/oss/OssArtifactSecurityScore.java (hunk 1 above)
Comment (sourabhsparkala) [reply src/main/java/com/sap/oss/phosphor/fosstars/model/score/oss/OssArtifactSecurityScore.java:88]: I agree with your argument. The artifact score should be co-dependent with the ProjectScore.

**Review by ManjunathMS35 — APPROVED** [review]
LGTM
