### PR TITLE
Fixes JSON mapping infinite recursion loop

### LINKED ISSUE #635: Jackson mapping infinite recursions
Facing this Jackson bidirectional issue leading to infinite recursions. This happens during de-serialization pertaining to security reviews. Not sure where the issue is:

For reference:
https://www.baeldung.com/jackson-bidirectional-relationships-and-infinite-recursion

```
com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: com.sap.oss.phosphor.fosstars.model.value.SecurityReviewsValue["reviews"]->com.sap.oss.phosphor.fosstars.model.value.SecurityReviews[0]->com.sap.oss.phosphor.fosstars.model.value.SecurityReview["subject"]->com.sap.oss.phosphor.fosstars.model.subject.oss.GitHubProject["ratingValue"]->com.sap.oss.phosphor.fosstars.model.value.RatingValue["scoreValue"]->com.sap.oss.phosphor.fosstars.model.value.ScoreValue["usedValues"]->java.util.ArrayList[6]->com.sap.oss.phosphor.fosstars.model.value.ScoreValue["usedValues"]->java.util.ArrayList[0]->com.sap.oss.phosphor.fosstars.model.value.SecurityReviewsValue["reviews"]->com.sap.oss.phosphor.fosstars.model.value.SecurityReviews[0]->com.sap.oss.phosphor.fosstars.model.value.SecurityReview["subject"]->com.sap.oss.phosphor.fosstars.model.subject.oss.GitHubProject["ratingValue"]->com.sap.oss.phosphor.fosstars.model.value.RatingValue["scoreValue"]->com.sap.oss.phosphor.fosstars.model.value.ScoreValue["usedValues"]->java.util.ArrayList[6]->com.sap.oss.phosphor.fosstars.model.value.ScoreValue["usedValues"]->java.util.ArrayList[0]->com.sap.oss.phosphor.fosstars.model.value.SecurityReviewsValue["reviews"]->com.sap.oss.phosphor.fosstars.model.value.SecurityReviews[0]->com.sap.oss.phosphor.fosstars.model.value.SecurityReview["subject"]->com.sap.oss.phosphor.fosstars.model.subject.oss.GitHubProject["ratingValue"]->com.sap.oss.phosphor.fosstars.model.value.RatingValue["scoreValue"]->com.sap.oss.phosphor.fosstars.model.value.ScoreValue["usedValues"]->java.util.ArrayList[6]->com.sap.oss.phosphor.fosstars.model.value.ScoreValue["usedValues"]->java.util.ArrayList[0]->com.sap.oss.phosphor.fosstars.model.value.SecurityReviewsValue["reviews"]->com.sap.oss.phosphor.fosstars.model.value.SecurityReviews[0]->com.sap.oss.phosphor.fosstars.model.value.SecurityReview["subject"]->com.sap.oss.phosphor.fosstars.model.subject.oss.GitHubProject["ratingValue"]->com.sap.oss.phosphor.fosstars.model.value.RatingValue["scoreValue"]->com.sap.oss.phosphor.fosstars.model.value.ScoreValue["usedValues"]->java.util.ArrayList[6]->com.sap.oss.phosphor.fosstars.model.value.ScoreValue["usedValues"]->java.util.ArrayList[0]->com.sap.oss.phosphor.fosstars.model.value.SecurityReviewsValue["reviews"]->com.sap.oss.phosphor.fosstars.model.value.SecurityReviews[0]->com.sap.oss.phosphor.fosstars.model.value.SecurityReview["subject"]->com.sap.oss.phosphor.fosstars.model.subject.oss.GitHubProject["ratingValue"]->com.sap.oss.phosphor.fosstars.model.value.RatingValue["scoreValue"]->com.sap.oss.phosphor.fosstars.model.value.ScoreValue["usedValues"]->java.util.ArrayList[6]->com.sap.oss.phosphor.fosstars.model.value.ScoreValue["usedValues"]->java.util.ArrayList[0]->com.sap.oss.phosphor.fosstars.model.value.SecurityReviewsValue["reviews"]->com.sap.oss.phosphor.fosstars.model.value.SecurityReviews[0]->com.sap.oss.phosphor.fosstars.model.value.SecurityReview["subject"]->com.sap.oss.phosphor.fosstars.model.subject.oss.GitHubProject["ratingValue"]->com.sap.oss.phosphor.fosstars.model.value.RatingValue["scoreValue"]->com.sap.oss.phosphor.fosstars.model.value.ScoreValue["usedValues"]->java.util.ArrayList[6]->com.sap.oss.phosphor.fosstars.model.value.ScoreValue["usedValues"]->java.util.ArrayList[0]->com.sap.oss.phosphor.fosstars.model.value.SecurityReviewsValue["reviews"]->com.sap.oss.phosphor.fosstars.model.value.SecurityReviews[0]->com.sap.oss.phosphor.fosstars.model.value.SecurityReview["subject"]->com.sap.oss.phosphor.fosstars.model.subject.oss.GitHubProject["ratingValue"]->com.sap.oss.phosphor.fosstars.model.value.RatingValue["scoreValue"]->com.sap.oss.phosphor.fosstars.model.value.ScoreValue["usedValues"]->java.util.ArrayList[6]->com.sap.oss.phosphor.fosstars.model.value.ScoreValue["usedValues"]->java.util.ArrayList[0]->com.sap.oss.phosphor.fosstars.model.value.SecurityReviewsValue["reviews"]->com.sap.oss.phosphor.fosstars.model.value.SecurityReviews[0]->com.sap.oss.phosphor.fosstars.model.value.SecurityReview["subject"]->com.sap.oss.phosphor.fosstars.model.subject.oss.GitHubProject["ratingValue"]->com.sap.oss.phosphor.fosstars.model.value.RatingValue["scoreValue"]->com.sap.oss.phosphor.fosstars.model.value.ScoreValue["usedValues"]->java.util.ArrayList[6]->com.sap.oss.phosphor.fosstars.model.value.ScoreValue["usedValues"]->java.util.ArrayList[0]->com.sap.oss.phosphor.fosstars.model.value.SecurityReviewsValue["reviews"]->com.sap.oss.phosphor.fosstars.model.value.SecurityReviews[0]->com.sap.oss.phosphor.fosstars.model.value.SecurityReview["subject"]->com.sap.oss.phosphor.fosstars.model.subject.oss.GitHubProject["ratingValue"]->com.sap.oss.phosphor.fosstars.model.value.RatingValue["scoreValue"]->com.sap.oss.phosphor.fosstars.model.value.ScoreValue["usedValues"]->java.util.ArrayList[6]->com.sap.oss.phosphor.fosstars.model.value.ScoreValue["usedValues"]->java.util.ArrayList[0]->com.sap.oss.phosphor.fosstars.model.value.SecurityReviewsValue["reviews"]->com.sap.oss.phosphor.fosstars.model.value.SecurityReviews[0]->com.sap.oss.phosphor.fosstars.model.value.SecurityReview["subject"]->com.sap.oss.phosphor.fosstars.model.subject.oss.GitHubProject["ratingValue"]->com.sap.oss.phosphor.fosstars.model.value.RatingValue["scoreValue"]->c
.......
```

DOD:
- Identify the root cause and fix the infinite recursion.
- Example https://github.com/envoyproxy/envoy

### PR DESCRIPTION
**Pull request by sourabhsparkala**
Fixes #635

### CODE REVIEW

File: src/main/java/com/sap/oss/phosphor/fosstars/data/github/GitHubCachingDataProvider.java [hunk 1]
```diff
@@ -42,7 +42,7 @@ public boolean supports(Subject subject) {
 
   @Override
   protected final ValueSet fetchValuesFor(Subject subject) throws IOException {
-    return fetchValuesFor(cast(subject, GitHubProject.class));
+    return fetchValuesFor(castAndCopy(subject, GitHubProject.class));
```
Comment (artem-smotrakov) [inline src/main/java/com/sap/oss/phosphor/fosstars/data/github/GitHubCachingDataProvider.java:45]: This update affects all data providers that extends `GitHubCachingDataProvider`. At lease it would result in multiple copies of subjects which increase memory usage. Although it may be safe for now, but do you have a strong reason to fix it in this class? As far as I understand, the problem is that `SecurityReview` has a subject. Would it be enough to make a shallow copy of a subject in `SecurityReviewsFromOpenSSF` and pass it to `SecurityReviews`s? It would break cycles, and would not affect other data providers.

File: src/main/java/com/sap/oss/phosphor/fosstars/model/Subject.java [hunk 2]
```diff
@@ -71,4 +73,18 @@
 
     return clazz.cast(subject);
   }
+
+  /**
+   * Clones a subject to avoid JSON mapping infinite recursion loop.
+   * The subject is cloned to a different entity.
```
Comment (artem-smotrakov) [inline src/main/java/com/sap/oss/phosphor/fosstars/model/Subject.java:79]: This method can be used for various purposes.

```suggestion
   * Clones a subject.
```

File: src/main/java/com/sap/oss/phosphor/fosstars/model/Subject.java [hunk 3]
```diff
@@ -71,4 +73,18 @@
...
+   *
+   * @param subject The subject.
+   * @param clazz The class.
+   * @param <T> The type.
+   * @return The subject.
```
Comment (artem-smotrakov) [inline src/main/java/com/sap/oss/phosphor/fosstars/model/Subject.java:84]:
```suggestion
   * @return A clone.
```

File: src/main/java/com/sap/oss/phosphor/fosstars/model/Subject.java [hunk 4]
```diff
@@ -71,4 +73,18 @@
...
+   * @throws IOException If subject is not cloneable.
```
Comment (artem-smotrakov) [inline src/main/java/com/sap/oss/phosphor/fosstars/model/Subject.java:85]:
```suggestion
   * @throws IOException If the subject could not be cloned.
```

File: src/main/java/com/sap/oss/phosphor/fosstars/data/github/SecurityReviewsFromOpenSSF.java [hunk 5]
```diff
@@ -83,7 +84,7 @@ public SecurityReviewsFromOpenSSF(GitHubDataFetcher fetcher) {
         if (!reviewDate.isPresent()) {
           continue;
         }
-        reviews.add(new SecurityReview(project, reviewDate.get()));
+        reviews.add(new SecurityReview(copy(project, GitHubProject.class), reviewDate.get()));
```
Comment (artem-smotrakov) [inline src/main/java/com/sap/oss/phosphor/fosstars/data/github/SecurityReviewsFromOpenSSF.java:87]: It is enough to make one clone and use it for all `SecurityReview`.

Comment (artem-smotrakov) [reply src/main/java/com/sap/oss/phosphor/fosstars/data/github/SecurityReviewsFromOpenSSF.java:87]: If I understand correctly, the loop occurs because the subject has a rating value. Do you know where this rating value comes from? Does it make sense to keep it in the copy?

Comment (artem-smotrakov) [reply src/main/java/com/sap/oss/phosphor/fosstars/data/github/SecurityReviewsFromOpenSSF.java:87]: In fact, I just realized that `SecurityReview.subject()` is not used at all. How about we just drop it? Since this class was introduced in `1.4.0`, it should be not break anything.

Comment (sourabhsparkala) [reply src/main/java/com/sap/oss/phosphor/fosstars/data/github/SecurityReviewsFromOpenSSF.java:87]: I considered this. Removing `subject` field. Then the `SecurityReview` class will hold only `date` field. It would not make sense to use this `SecurityReview` class at all. 

Then I wondered why this was introduced in the first place. For example consider a project with multiple artifacts. Then is there a possibility that each `subject` could have different `SecurityReviews`? 

Does it make sense?

Comment (sourabhsparkala) [reply src/main/java/com/sap/oss/phosphor/fosstars/data/github/SecurityReviewsFromOpenSSF.java:87]: > If I understand correctly, the loop occurs because the subject has a rating value. Do you know where this rating value comes from? Does it make sense to keep it in the copy?

Yes I found it, it happens here https://github.com/SAP/fosstars-rating-core/blob/master/src/main/java/com/sap/oss/phosphor/fosstars/tool/SingleRatingCalculator.java#L127 -> The `RatingValue` is set.

Comment (artem-smotrakov) [reply src/main/java/com/sap/oss/phosphor/fosstars/data/github/SecurityReviewsFromOpenSSF.java:87]: > Then the `SecurityReview` class will hold only `date` field. It would not make sense to use this `SecurityReview` class at all.

Currently, the security review scoring function doesn't use the subject. The function just checks whether or not the project had security review in the past. So, I think it still makes sense to use the class. Furthermore, #586 is going to introduce a new filed in the security review, and the scoring function is going to use the review date as well.

> Then I wondered why this was introduced in the first place. For example consider a project with multiple artifacts. Then is there a possibility that each `subject` could have different `SecurityReviews`?

When a rating is being calculated, each feature value is connected to a subject. Most of values are connected to the subject implicitly by storing them in a value set. Currently, only `SecurityReview` has an implicit link. If you drop the field `subject`, the explicit link via the value set will be there. If you'd like to calculate ratings for multiple subject, you need to put them in separate values sets anyway. Moreover, we don't really have security reviews for artifacts. I am not sure it makes sense at all.

Comment (sourabhsparkala) [reply src/main/java/com/sap/oss/phosphor/fosstars/data/github/SecurityReviewsFromOpenSSF.java:87]: Ok, then I shall remove the subject and also remove the cloning part.

File: src/test/java/com/sap/oss/phosphor/fosstars/model/value/SecurityReviewsValueTest.java [hunk 6]
```diff
@@ -25,4 +27,24 @@ public void testJsonSerialization() throws IOException {
     assertTrue(value.equals(clone) && clone.equals(value));
     assertEquals(value.hashCode(), clone.hashCode());
   }
+
+  @Test
+  public void testNoInfiniteRecursionLoopExists() throws IOException {
+    GitHubProject project = new GitHubProject("org", "test");
```
Comment (artem-smotrakov) [inline src/test/java/com/sap/oss/phosphor/fosstars/model/value/SecurityReviewsValueTest.java:33]: `project` is not used anymore. The test case is a dup of the one above. Please remove it.

**Review by artem-smotrakov — CHANGES_REQUESTED** [review]

**Review by artem-smotrakov — APPROVED** [review]
