### PR TITLE
Fix #217: Use synchronized map

### LINKED ISSUE #217: Handling of `localRepositoriesInfo` in `GitHubDataFetcher` is not thread safe.
Handling of `localRepositoriesInfo` in `GitHubDataFetcher` is not thread safe.
If using only one instance of `GitHubDataFetcher` the `cleanup` method throws `ConcurrentModificationException` if a) it is called parallel or b) if during cleanup a new element is added.

Tested with use of a synchronized map and a synchronized block for the clean up.
See PR #218 

In addition I would like to have the option to replace the used `GitHub` instance.
Would it be possible to make it not final and add a `setGitHub` method?
If yes I can create an issue / PR for this 🙂

### PR DESCRIPTION
**Pull request by mibo**
Synchronize access to `localRepositoriesInfo` in `GitHubDataFetcher`.

This closes #217

### CODE REVIEW

**Comment by artem-smotrakov** [comment]
@mibo You can go ahead and add a `set(GitHub github)` method that updates a `GitHub` instance. Please make it thread-safe. Did you check if the rest of the `GitHubDataFetcher` is thread-safe? I think we need to make it completely thread-safe.

File: src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java [hunk 1]
```diff
@@ -148,7 +149,7 @@ public GitHubDataFetcher(GitHub github, Path base) throws IOException {
     this.base = base;
     this.github = github;
 
-    this.localRepositoriesInfo = loadLocalRepositoriesInfo();
+    this.localRepositoriesInfo = Collections.synchronizedMap(loadLocalRepositoriesInfo());
```
Comment (artem-smotrakov) [inline src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java:152]: Since you you `localRepositoriesInfo` is a synchronized block, is it necessary to use a synchronized map?

Comment (mibo) [reply src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java:152]: I would say yes, otherwise it may lead to that in the `localRepositoryFor` method new items are added during the `cleanup` run.

**Comment by mibo** [comment]
> @mibo You can go ahead and add a `set(GitHub github)` method that updates a `GitHub` instance. Please make it thread-safe. 

Should I create a separate issue / PR for this?

> Did you check if the rest of the `GitHubDataFetcher` is thread-safe? I think we need to make it completely thread-safe.

Had a look and the rest looks fine for me. 
In addition I checked the `GitHubDataCache` and looks also good.

**Comment by artem-smotrakov** [comment]
> > @mibo You can go ahead and add a `set(GitHub github)` method that updates a `GitHub` instance. Please make it thread-safe.
> 
> Should I create a separate issue / PR for this?

Updating this pull request is fine.

> 
> > Did you check if the rest of the `GitHubDataFetcher` is thread-safe? I think we need to make it completely thread-safe.
> 
> Had a look and the rest looks fine for me.
> In addition I checked the `GitHubDataCache` and looks also good.

Okay, let me have another look.

File: src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java (hunk 1 above)
Comment (artem-smotrakov) [reply src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java:152]: Then, should those methods also access the map in a synchronized block? I think that using both synchronized blocks and a synchronized map is redundand.

**Comment by artem-smotrakov** [comment]
> > Did you check if the rest of the `GitHubDataFetcher` is thread-safe? I think we need to make it completely thread-safe.
> 
> Had a look and the rest looks fine for me.
> In addition I checked the `GitHubDataCache` and looks also good.

I think the rest of fields in the class need to be synchronized as well to make the class thread-safe.

**Comment by mibo** [comment]
> > Had a look and the rest looks fine for me.
> > In addition I checked the `GitHubDataCache` and looks also good.
> 
> I think the rest of fields in the class need to be synchronized as well to make the class thread-safe.

Hm, I'm not the expert for concurrency but in `GitHubDataCache` the `entries` (`LRUMap`) is used in a way that I expect in worst case that the fetcher use a cache entry which in parallel gets removed.
Because the `GitHubDataCache.get(..)` anyways return `Optional`.

To be on the very safe side we can wrap the `entries` map:
`this.entries = Collections.synchronizedMap(new LRUMap<>(CACHE_CAPACITY, SCAN_UNTIL_REMOVABLE));`

WDYT?

**Comment by artem-smotrakov** [comment]
The `repositoryFor()` method reads and writes data to `repositoryCache`. I think it may cause a race. Therefore, I think that `repositoryCache` needs to be accessed in a synchronized block or `GitHubDataCache` needs to be made thread-safe.

The same is for `localRepositoriesInfo` and `localRepositories`.

Furthermore, the `loadLocalRepositoryFor()` method works with the local repositories. That also needs to be synchronized between multiple instances of the class since all of them use the same directory.

**Comment by mibo** [comment]
> The `repositoryFor()` method reads and writes data to `repositoryCache`. I think it may cause a race. Therefore, I think that `repositoryCache` needs to be accessed in a synchronized block or `GitHubDataCache` needs to be made thread-safe.

As mentioned guess the worst what can happen is that in the `repositoryFor` method a `GHRepository` is used which just got removed from the cache.
But to be on the safe side the `LRUMap` in `GitHubDataCache` can be wrapped.

> The same is for `localRepositoriesInfo` and `localRepositories`.
> 
> Furthermore, the `loadLocalRepositoryFor()` method works with the local repositories. That also needs to be synchronized between multiple instances of the class since all of them use the same directory.

Yes, I missed this as I confused myself with `loadLocalRepositoriesInfo` and `loadLocalRepositoryFor`.
Agree that a `synchronized` block should be added to `loadLocalRepositoryFor` and the `storeLocalRepositoriesInfo`.
For the `loadLocalRepositoriesInfo` guess it is not required as it is only called in the constructor.
But as it can be called by extending classes guess it is better to add a `synchronized` block.

Will update the PR accordingly.

File: src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java (hunk 1 above)
Comment (mibo) [reply src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java:160]: Yes, with adding the additional `synchronized` blocks the wrapping is not mandatory.
But removing it also does not really change anything regarding performance (afaik).
And keeping it makes it at least clear / safe in case of modifications in the future.

Comment (artem-smotrakov) [reply src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java:160]: > Yes, with adding the additional `synchronized` blocks the wrapping is not mandatory.

Then, let's please avoid duplicating synchronization.

> But removing it also does not really change anything regarding performance (afaik).

Most likely we won't notice that, but it does.

> And keeping it makes it at least clear / safe in case of modifications in the future.

I am sorry but I don't see how it make it clearer and safer. Let's please avoid duplicating synchronization.

Comment (mibo) [reply src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java]: > > But removing it also does not really change anything regarding performance (afaik).
> 
> Most likely we won't notice that, but it does.

Did not know this. Always thought performance is equal if the `synchronized` block is `synchronized` on the same object which is wrapped via the `Collections.synchronized...`.
And in our case the `localRepositoriesInfo`.
But thanks for this info 🙂

> > And keeping it makes it at least clear / safe in case of modifications in the future.
> 
> I am sorry but I don't see how it make it clearer and safer. Let's please avoid duplicating synchronization.

Done.

File: src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataCache.java [hunk 2]
```diff
@@ -71,7 +73,7 @@ public int size() {
    * Returns the maximum size of the cache.
    */
   public int maxSize() {
-    return entries.maxSize();
+    return CACHE_CAPACITY;
```
Comment (artem-smotrakov) [inline src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataCache.java:76]: Is this update required?

File: src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java [hunk 3]
```diff
@@ -126,6 +127,14 @@ public GitHub github() {
     return github;
   }
 
+  /**
+   * Set the interface to the GitHub API.
+   */
+  public void github(GitHub github) {
```
Comment (artem-smotrakov) [inline src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java:133]: Could you please rename it to `set()`? I think that the `github` field needs also be synchronized.

File: src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java [hunk 4]
```diff
@@ -210,44 +219,46 @@ public LocalRepository localRepositoryFor(GitHubProject project) throws IOExcept
   private LocalRepository loadLocalRepositoryFor(GitHubProject project) throws IOException {
     Objects.requireNonNull(project, "On no! Project is null!");
 
-    LocalRepositoryInfo info = localRepositoriesInfo.get(project.url());
-    if (info == null) {
-      Path repositoryPath = base
-          .resolve(project.organization().name())
-          .resolve(project.name());
+    synchronized (localRepositoriesInfo) {
```
Comment (artem-smotrakov) [inline src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java:222]: I am afraid that using a monitor of the `localRepositoriesInfo` field is not enough. The `loadLocalRepositoryFor()` method accesses cloned repositories and keep info about them in the `localRepositoriesInfo` map. When an instance of `GitHubDataFetcher` is used in multiple threads, then a lock on `localRepositoriesInfo` is going to protect the map from a race. However, when we have multiple instances of `GitHubDataFetcher`, then calling the`loadLocalRepositoryFor()` method on them is going to result concurrent access to the filesystem. I think the method should use a monitor of a static constant that is shared between all instances of the class. Or, the method can use a lock-file in the filesystem.

Comment (mibo) [reply src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java:222]: Perhaps a bit late to ask this. 
But do you think about making it thread-safe for use as singleton only would be better?
In combination with adding according static method to get (create) the singleton instance?

File: src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java (hunk 3 above)
Comment (mibo) [reply src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java:133]: I wanted to name it `setGithub` but after I have seen the `github()` method without `get...` I thought without `set` is preferred 🙂
Regarding synchronized for the github field I guess I do not understand it.
Would it make a real difference if the get/set for `github` have a synchronized block?

File: src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataCache.java (hunk 2 above)
Comment (mibo) [reply src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataCache.java:76]: With the wrapping of the LRUMap I had to change the `entrie` field to `Map`.
As result I need to cast the `entries` to access the max size method.
Or I thought the max size is always the same as the static final value of `CACHE_CAPACITY`.

But I'm open for other options.

File: src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java (hunk 3 above)
Comment (artem-smotrakov) [reply src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java:133]: > I wanted to name it `setGithub` but after I have seen the `github()` method without `get...` I thought without `set` is preferred 

I meant `public void set(GitHub github) {`.

> Regarding synchronized for the github field I guess I do not understand it.
> Would it make a real difference if the get/set for `github` have a synchronized block?

Since the `github` field is not final anymore, multiple threads can read and write to the `github` field. Therefore, all access to this field needs to be synchronized.

File: src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java (hunk 4 above)
Comment (artem-smotrakov) [reply src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java:222]: I am not sure what you mean and why it is late. Do you suggest to make it a singleton?

I suggest to use the following:

```
private static final Object localRepositoryLock = new Object();
...
synchronized (localRepositoryLock) {
  ... work with local repositories
}
```

File: src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataCache.java (hunk 2 above)
Comment (artem-smotrakov) [reply src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataCache.java:76]: Okay.

File: src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java (hunk 4 above)
Comment (mibo) [reply src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java:222]: No, I do not see a problem. 
Just thought make `GitHubDataFetcher` is less effort 😄 
Will update it accordingly.

File: src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java (hunk 3 above)
Comment (mibo) [reply src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java:133]: Still not sure if this would make a bit difference.
But I will update it as proposed and for a detailed explanation we use another channel 🙂

Comment (artem-smotrakov) [reply src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java:133]: Most likely you won't see any difference. If `github` is not synchronized, and you use multiple instances of `GitHub`, then you can't tell which one is used for sure once you update the field. I would like to make the class completely thread-safe.

File: src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java (hunk 4 above)
Comment (artem-smotrakov) [reply src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java:222]: Sure.

> Just thought make GitHubDataFetcher is less effort

Sorry, didn't get it. To make it what?

Comment (mibo) [reply src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java:222]: Sorry, missed _singleton_

File: src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java (hunk 3 above)
Comment (mibo) [reply src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java:133]: Still not sure about this. 
But I trust you as you have more knowledge about concurrency than I 🙂

File: src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java (hunk 4 above)
Comment (artem-smotrakov) [reply src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java]: No, I am not sure if making it a singleton would be less effort. This change would result to updating all data provider and their tests.

Comment (mibo) [reply src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java]: Yes, you are right. Have not thought about this.

File: src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java [hunk 5]
```diff
@@ -210,58 +223,60 @@ public LocalRepository localRepositoryFor(GitHubProject project) throws IOExcept
   private LocalRepository loadLocalRepositoryFor(GitHubProject project) throws IOException {
     Objects.requireNonNull(project, "On no! Project is null!");
 
-    LocalRepositoryInfo info = localRepositoriesInfo.get(project.url());
-    if (info == null) {
-      Path repositoryPath = base
-          .resolve(project.organization().name())
-          .resolve(project.name());
+    synchronized (LOCAL_REPOSITORIES_LOCK) {
+      LocalRepositoryInfo info = localRepositoriesInfo.get(project.url());
```
Comment (artem-smotrakov) [inline src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java:227]: Strictly speaking, `localRepositoriesInfo` should be static. But let's leave it as-is for now. We'll consider this update later.

**Comment by artem-smotrakov** [comment]
> Could you please synchronize `pullInterval` and `github` as well? I think if we should make the class completely thread-safe.

@mibo

**Comment by artem-smotrakov** [comment]
@mibo Do you have a test for the updates?

**Comment by mibo** [comment]
> @mibo Do you have a test for the updates?

Not yet, thought we should first finish the changes in the class(es) and than I would add the tests.

**Comment by mibo** [comment]
> > Could you please synchronize `pullInterval` and `github` as well? I think if we should make the class completely thread-safe.
> 
> @mibo

Is it not enough to add the `synchronized` to the get/set methods?
Guess I have to read some more about concurrency in java to fully understand it.

**Comment by artem-smotrakov** [comment]
> > > Could you please synchronize `pullInterval` and `github` as well? I think if we should make the class completely thread-safe.
> > 
> > 
> > @mibo
> 
> Is it not enough to add the `synchronized` to the get/set methods?
> Guess I have to read some more about concurrency in java to fully understand it.

My bad, I noticed that you added `synchronized` to the methods after I posted my comment.

File: src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java [hunk 6]
```diff
@@ -81,13 +81,14 @@
...
    */
-  private final GitHub github;
+  private GitHub github;
 
   /**
    * A limited capacity cache to store the repository of a {@link GitHubProject}.
    */
   private final GitHubDataCache<GHRepository> repositoryCache = new GitHubDataCache<>();
 
+
```
[the remark this answers is not in the document]
Comment (mibo) [reply src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java]: Done

**Comment by artem-smotrakov** [comment]
> > @mibo Do you have a test for the updates?
> 
> Not yet, thought we should first finish the changes in the class(es) and than I would add the tests.

Okay, up to you. I usually add tests right away to make sure that the new stuff work fine.

**Comment by artem-smotrakov** [comment]
@mibo Thanks for the improving `GitHubDataFetcher`. The updates are in master now. I just updated the commit message to refer to the issue.
