### PR TITLE
Bug fixes

### LINKED ISSUE #545: UsesOwaspDependencyCheck fails with IllegalArgumentException due to a wrong CVSS
While calculating a security rating for https://github.com/apache/struts , the provider failed with the following exception:

```
[+] Figuring out if the project uses OWASP Dependency Check ...
[!] Holy Moly, UsesOwaspDependencyCheck data provider failed!
[!] The last thing that it said was
java.lang.IllegalArgumentException: What the heck? 11.000000 doesn't look like a CVSS score!
        at com.sap.oss.phosphor.fosstars.model.value.CVSS.check(CVSS.java:141)
        at com.sap.oss.phosphor.fosstars.model.value.OwaspDependencyCheckCvssThresholdValue.<init>(OwaspDependencyCheckCvssThresholdValue.java:33)
        at com.sap.oss.phosphor.fosstars.model.feature.OwaspDependencyCheckCvssThreshold.value(OwaspDependencyCheckCvssThreshold.java:28)
        at java.util.Optional.map(Optional.java:215)
        at com.sap.oss.phosphor.fosstars.data.github.UsesOwaspDependencyCheck.checkMaven(UsesOwaspDependencyCheck.java:142)
        at com.sap.oss.phosphor.fosstars.data.github.UsesOwaspDependencyCheck.fetchValuesFor(UsesOwaspDependencyCheck.java:80)
        at com.sap.oss.phosphor.fosstars.data.github.UsesOwaspDependencyCheck.fetchValuesFor(UsesOwaspDependencyCheck.java:47)
        at com.sap.oss.phosphor.fosstars.data.AbstractCachingDataProvider.doUpdate(AbstractCachingDataProvider.java:64)
        at com.sap.oss.phosphor.fosstars.data.AbstractCachingDataProvider.doUpdate(AbstractCachingDataProvider.java:21)
        at com.sap.oss.phosphor.fosstars.data.AbstractDataProvider.update(AbstractDataProvider.java:75)
        at com.sap.oss.phosphor.fosstars.data.AbstractDataProvider.update(AbstractDataProvider.java:19)
        at com.sap.oss.phosphor.fosstars.tool.github.SingleRatingCalculator.calculateFor(SingleRatingCalculator.java:98)
        at com.sap.oss.phosphor.fosstars.tool.github.SingleRatingCalculator.calculateFor(SingleRatingCalculator.java:21)
        at com.sap.oss.phosphor.fosstars.tool.github.MultipleRatingsCalculator.calculateFor(MultipleRatingsCalculator.java:120)
        at com.sap.oss.phosphor.fosstars.tool.github.MultipleRatingsCalculator.calculateFor(MultipleRatingsCalculator.java:96)
        at com.sap.oss.phosphor.fosstars.tool.github.MultipleRatingsCalculator.calculateFor(MultipleRatingsCalculator.java:138)
        at com.sap.oss.phosphor.fosstars.tool.github.Application.processConfig(Application.java:495)
        at com.sap.oss.phosphor.fosstars.tool.github.Application.run(Application.java:356)
        at com.sap.oss.phosphor.fosstars.tool.github.Application.main(Application.java:160)
```

### LINKED ISSUE #546: OssSecurityRatingMarkdownReporter fails to deserialize data
While creating a report with a config, the command-line tool fails to load data:

```
[+] Loading config from docs/oss/security/spring.yml
[x] Something went wrong!
com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve subtype of [simple type, class com.sap.oss.phosphor.fosstars.model.subject.oss.GitHubProject]: missing type id property 'type'
 at [Source: (sun.nio.ch.ChannelInputStream); line: 9598, column: 1] (through reference chain: java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43)
	at com.fasterxml.jackson.databind.DeserializationContext.missingTypeIdException(DeserializationContext.java:1943)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingTypeId(DeserializationContext.java:1456)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._handleMissingTypeId(TypeDeserializerBase.java:307)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedUsingDefaultImpl(AsPropertyTypeDeserializer.java:178)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:115)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1292)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:357)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3593)
	at com.sap.oss.phosphor.fosstars.tool.github.AbstractReporter.loadProjects(AbstractReporter.java:103)
	at com.sap.oss.phosphor.fosstars.tool.github.AbstractReporter.loadProjects(AbstractReporter.java:83)
	at com.sap.oss.phosphor.fosstars.tool.github.OssSecurityRatingMarkdownReporter.<init>(OssSecurityRatingMarkdownReporter.java:149)
	at com.sap.oss.phosphor.fosstars.tool.github.Application.reporterFrom(Application.java:683)
	at com.sap.oss.phosphor.fosstars.tool.github.Application.makeReporters(Application.java:662)
	at com.sap.oss.phosphor.fosstars.tool.github.Application.processConfig(Application.java:477)
	at com.sap.oss.phosphor.fosstars.tool.github.Application.run(Application.java:356)
	at com.sap.oss.phosphor.fosstars.tool.github.Application.main(Application.java:160)
```

### LINKED ISSUE #547: Deserialization of VersionRange fails
Serialization/deserialization of `VersionRange` doesn't seem to work.

```java
    VersionRange range = new VersionRange("1.2", "2.3");
    VersionRange clone = Json.read(Json.toBytes(range), VersionRange.class);
    assertEquals(range, clone);
```

This test fails with the following error:

```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (byte[])"{
  "versionStart" : {
    "present" : true
  },
  "versionEnd" : {
    "present" : true
  }
}"; line: 2, column: 20] (through reference chain: com.sap.oss.phosphor.fosstars.model.value.VersionRange["versionStart"])

	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1601)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1375)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1280)
	at com.fasterxml.jackson.databind.DeserializationContext.extractScalarFromObject(DeserializationContext.java:872)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:62)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:565)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:449)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3609)
	at com.sap.oss.phosphor.fosstars.util.Json.read(Json.java:42)
	at com.sap.oss.phosphor.fosstars.model.value.VersionRangeTest.testSerializationWithJson(VersionRangeTest.java:14)
```

### PR DESCRIPTION
**Pull request by artem-smotrakov**
This pull requests addresses several issues that were found while re-building the report for well-known open source projects.

Fixes #545
Fixes #546
Fixes #547

### CODE REVIEW

File: src/main/java/com/sap/oss/phosphor/fosstars/model/value/VersionRange.java [hunk 1]
```diff
@@ -1,34 +1,32 @@
...
    */
   private final String versionEnd;
 
   /**
-   * Create a version range with start and end version.
+   * Create a version range with start and end versions.
    * Both versions are including.
    * Start and end version may be null.
    *
-   * @param versionStart start version (including)
```
Comment (sourabhsparkala) [inline src/main/java/com/sap/oss/phosphor/fosstars/model/value/VersionRange.java:30]: As I understand. We do not have any way of deciding if the end or start versions is including or excluding. Atleast we have not implemented anything to address this. Do we not mention that as part of doc?

File: src/main/java/com/sap/oss/phosphor/fosstars/model/value/VersionRange.java [hunk 2]
```diff
@@ -38,13 +36,21 @@ public VersionRange(
...
   }
 
-  @JsonGetter("versionStart")
-  public Optional<String> versionStart() {
+  /**
+   * Returns the start version.
+   *
+   * @return The start version if available.
+   */
+  public Optional<String> start() {
```
Comment (sourabhsparkala) [inline src/main/java/com/sap/oss/phosphor/fosstars/model/value/VersionRange.java:44]: I think this would have fixed it? https://github.com/SAP/fosstars-rating-core/blob/master/src/main/java/com/sap/oss/phosphor/fosstars/model/subject/oss/MavenArtifact.java#L13

File: src/main/java/com/sap/oss/phosphor/fosstars/model/value/Vulnerability.java [hunk 3]
```diff
@@ -485,25 +485,25 @@ public Builder set(CVSS cvss) {
...
      *
-     * @param resolution The resolution status.
+     * @param references The references.
      * @return The same builder.
      */
-    public Builder set(Resolution resolution) {
-      this.resolution = Objects.requireNonNull(resolution, "Null is not a resolution!");
+    public Builder references(List<Reference> references) {
+      Objects.requireNonNull(references, "Oh no! References is null!");
+      this.references = references;
```
Comment (sourabhsparkala) [inline src/main/java/com/sap/oss/phosphor/fosstars/model/value/Vulnerability.java:506]:
```suggestion
      this.references = Objects.requireNonNull(references, "Oh no! References is null!");
```

**Review by sourabhsparkala — COMMENTED** [review]
@Artem please have a look

File: src/main/java/com/sap/oss/phosphor/fosstars/model/value/VersionRange.java (hunk 1 above)
Comment (artem-smotrakov) [reply src/main/java/com/sap/oss/phosphor/fosstars/model/value/VersionRange.java:30]: > We do not have any way of deciding if the end or start versions is including or excluding.

No, the class doesn't control it. Even if we mention "including" or "excluding" in the docs, the caller is free to follow it or not.

> Atleast we have not implemented anything to address this

No, we haven't. To be honest, I am not sure that we need it.

File: src/test/java/com/sap/oss/phosphor/fosstars/tool/github/MergedJsonReporterTest.java [hunk 4]
```diff
@@ -0,0 +1,43 @@
...
+import java.nio.file.Path;
+import java.util.List;
+import org.apache.commons.io.FileUtils;
+import org.junit.Test;
+
+public class MergedJsonReporterTest {
+
+  @Test
+  public void testLoadAndSave() throws IOException {
+    Path path = Files.createTempFile(MergedJsonReporterTest.class.getName(), "test");
```
Comment (sourabhsparkala) [inline src/test/java/com/sap/oss/phosphor/fosstars/tool/github/MergedJsonReporterTest.java:21]: Do we not introduce `GitHubOrganization` for the serialization and deserialization test here?

File: src/main/java/com/sap/oss/phosphor/fosstars/data/github/UsesOwaspDependencyCheck.java [hunk 5]
```diff
@@ -139,6 +140,7 @@ private static ValueSet checkMaven(LocalRepository repository) throws IOExceptio
         OwaspDependencyCheckUsageValue usage = OWASP_DEPENDENCY_CHECK_USAGE.value(visitor.usage());
 
         OwaspDependencyCheckCvssThresholdValue threshold = visitor.threshold()
+            .filter(value -> CVSS.MIN <= value && value <= CVSS.MAX)
```
Comment (sourabhsparkala) [inline src/main/java/com/sap/oss/phosphor/fosstars/data/github/UsesOwaspDependencyCheck.java:143]: Could you please confirm?
- If lets say that `filter()` returns empty list.
- Then would `orElse` return the `notSpecifiedValue`?
- What is the value = 12?

Comment (sourabhsparkala) [reply src/main/java/com/sap/oss/phosphor/fosstars/data/github/UsesOwaspDependencyCheck.java:143]: I guess the corresponding test is actually testing that?

**Review by sourabhsparkala — APPROVED** [review]
Looks good to me. @artem-smotrakov one clarification required though.

File: src/main/java/com/sap/oss/phosphor/fosstars/data/github/UsesOwaspDependencyCheck.java (hunk 5 above)
Comment (artem-smotrakov) [reply src/main/java/com/sap/oss/phosphor/fosstars/data/github/UsesOwaspDependencyCheck.java:143]: `filter()` doesn't return a list, it returns an `Optional`. The predicate in `filter()` checks that `value` is a valid CVSS, otherwise it returns an empty `Optional` that results in a not specified threshold. This check is necessary because `failBuildOnCVSS` tag can contain any number.

> I guess the corresponding test is actually testing that?

Yes, it is covered in the new test case.
