### PR TITLE
Fixes ConcurrentModificationException issue in GitHubDataFetcher

### LINKED ISSUE #206: `cleanUp` in `GitHubDataFetcher` leads to exception
During iteration over the `localRepositoriesInfo` the deleted items are removed from the map [see here](https://github.com/SAP/fosstars-rating-core/blob/0fb216dca734b23d34a18eb7e20e13a237ecb26d/src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java#L389).

This leads to a `java.util.ConcurrentModificationException`.

Suggestion: in the loop collect deleted items and remove them after the iteration is finished.

### PR DESCRIPTION
**Pull request by mibo**
This closes #206

### CODE REVIEW

File: src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java [hunk 1]
```diff
@@ -386,9 +389,10 @@ public void cleanup(CleanupStrategy strategy) {
           LOGGER.error(
               () -> String.format("Could not delete a local repository: %s", info.path()), e);
         }
-        localRepositoriesInfo.remove(url);
+        toBeRemoved.remove(url);
```
Comment (artem-smotrakov) [inline src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java:392]: Did you mean to add a URL to the set?

```suggestion
        toBeRemoved.add(url);
```

File: src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java [hunk 2]
```diff
@@ -386,9 +389,10 @@ public void cleanup(CleanupStrategy strategy) {
...
       }
     }
+    toBeRemoved.forEach(localRepositoriesInfo::remove);
```
Comment (artem-smotrakov) [inline src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java:395]: `Set.removeAll()` can also be used but not a big deal.

File: src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java (hunk 1 above)
Comment (mibo) [reply src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java]: 🙈 Sure, this would make a lot more sense 🙂

File: src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java (hunk 2 above)
Comment (mibo) [reply src/main/java/com/sap/sgs/phosphor/fosstars/data/github/GitHubDataFetcher.java:395]: Afaik `Set.removeAll()` can not be used at we want to remove the `URL`s from the map (which does not over a `removeAll()` method).

**Comment by mibo** [comment]
Thanks for quick review and merge.
